name: disposabletrends
favicon: null
layout_spectrum: 0.0016400660388171673
typography_spectrum: 0.5297188011463732
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6512314165011048
  lightness: 0.8200735347345471
  saturation: 0.01168702240101993
  rhythmicContrast: 0.6893394824583083
purpose: []
