name: disposabletrends
favicon: null
layout_spectrum: 0.0016400660388171673
typography_spectrum: 0.5297188011463732
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#061117'
    - '#ffffff'
    - '#11447b'
    - '#e2beae'
    - '#958892'
  brandStrength: 0.875
  lightness: 0.25
  saturation: 0.3125
  rhythmicContrast: 0
purpose: []
