name: disposabletrends
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3239
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#061117'
    - '#ffffff'
    - '#11447b'
    - '#e2beae'
    - '#958892'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
